artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/ml/datasets/wine+quality
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion